source 'https://rubygems.org'

gem 'beaker'
gem 'beaker-puppet_install_helper'
gem 'beaker-rspec'
gem 'beaker-vagrant'
gem 'metadata-json-lint'
gem 'puppet', '~>6.0'
gem 'puppetlabs_spec_helper'
gem 'rake'
gem 'rspec'
gem 'rspec-puppet'
gem 'rspec-puppet-facts'
gem 'rubocop'
gem 'semantic_puppet'
